### ISSUE TITLE
Изменение операндов операции multiply()

### ISSUE THREAD

**Issue by arcturus5340** [thmbele/neotheone#1]
Вызов `neo.multiply()` приводит к изменению параметров функции. 
К ошибке приводит следующая строка кода, где возвращаемому значению функции `big_field` присваиваются объекты `a` или `b` в зависимости от их размерности:
```    
function multiply(a,b: field): field;
     begin
         var (big_field, small_field) := a.shape.Product > b.shape.Product?
                                            (a, b) : (b, a);
        ...
```
Возможным решением служит создание нового объекта `field` для переменной `big_field` или создание и использование для присваивания нового метода класса `field`, что будет возвращать копию объекта `field`. (Отличным примером такого метода является `numpy.copy()`)

**Comment by more-suo** [comment]
Спасибо за Ваш отзыв! Я очень сожалею, что пришло к этому... Вчера утром я эту ошибку устранил! через тот же `field.copy()`, как Вы и посоветовали.
