### ISSUE TITLE
Поддержка многомерных массивов

### ISSUE THREAD

**Issue by arcturus5340** [thmbele/neotheone#3]
Поддержка многомерных массивов классом `neo.field` должна сильно расширить функционал библиотеки, но вместе с тем и несколько усложнить его. Моя идея заключается в введении указателей в код программы и работе с массивами на уровне памяти, лишенным абстракций. 
Так, например, может выглядеть конструктор класса `neo.field`, поддерживающий многомерные массивы:
```
constructor Create(array_pointer: pointer; shape: array of integer);
var true_array_pointer : ^^real;
    element_pointer : ^real;
begin
  true_array_pointer :=  array_pointer;
  true_array_pointer := pointer(integer(true_array_pointer^)+40);
  for var index := 0 to shape.Product-1 do
    begin
    element_pointer := pointer(integer(true_array_pointer)+index*sizeof(real));   
    writeln(element_pointer^);
    end;
end;
```
Результатом работы данного фрагмента кода будет вывод всех элементов массива по данному указателю на массив и его форме. Использование данного конструктора показано в следующем примере:
```
var arr_x: array [,,] of real := (
                                  ((1.0, 2.0), (3.0, 4.0)), 
                                  ((5.0, 6.0), (7.0, 8.0))
                                 );
var shape: array of integer := (2, 2, 2);
var x := new neo.field(@arr_x, shape);
```

**Comment by arcturus5340** [comment]
Беру разработку этой фичи в свои руки. Сделал форк. В скором времени (~неделя) реализую поддержку многомерности и постараюсь оптимизировать код. С пулл реквестом опишу все новые возможности/изменения наиболее детально

**Comment by more-suo** [comment]
спасибо, уважаемый Арктурус, за Ваще сотрудничество в столь сложный период!

**Comment by arcturus5340** [comment]
Предложен на рассмотрение пулл реквест #6 с реализацией поддержки многомерных массивов - тензоров

**Comment by more-suo** [comment]
спасибо большое!
