### ISSUE TITLE
Где можно связаться с разработчиками?

### ISSUE THREAD

**Issue by EmilyGraceSeville7cf** [thmbele/neotheone#4]
Имеется ли официальный форум? Хотелось бы побеседовать.

**Comment by more-suo** [comment]
> Имеется ли официальный форум? Хотелось бы побеседовать. 

напишите на почту! th.mbele@gmail.com

**Comment by arcturus5340** [comment]
Проекту всего около двух недель, так что форума у нас нет)
Но Вы можете писать сюда или на почту arcturus5340@gmail.com
