### ISSUE TITLE
Приватные атрибуты - публичны

### ISSUE THREAD

**Issue by more-suo** [thmbele/neotheone#7]
Важные атрибуты, которые должны быть приватными - публичны: rank, length и shape. Предлагаю сделать их приватными, если это не специальная задумка разработчиков.

**Comment by arcturus5340** [comment]
Исправил на время. Неплохо было бы хранить `ndarray.shape` в виде кортежа

**Comment by EmilyGraceSeville7cf** [comment]
С точки зрения неограниченности размера - лучше массив.

**Comment by arcturus5340** [comment]
Вы абсолютно правы, массивы стоит инкапсулировать и оставить - это оптимальнее в данном случае
